name: GitHub Actions Demo
run-name:  ${{ github.actor }} 
on: [push]
jobs:
  mail_on_push: 
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}      
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Uus push
          to: triintahk@gmail.com
          from: Github actions
          body:  Lisati uus push ${{github.repository}}!
